services:
  youdeyiwu:
    labels:
      - maintainer=dafengzhen
      - description=Run youdeyiwu backend application
    container_name: youdeyiwu
    image: "dafengzhen/youdeyiwu:${TAG}"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://youdeyiwu-db:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      youdeyiwu-db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - logs:/youdeyiwu/logs
    ports:
      - "8080:8080"
    networks:
      - youdeyiwu

  youdeyiwu-web:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu frontend application
    container_name: youdeyiwu-web
    image: "dafengzhen/youdeyiwu-web:${TAG}"
    environment:
      - URL
      - NAME
      - DESCRIPTION
      - SHOW_LANGUAGE_SWITCHER
      - API_SERVER=http://youdeyiwu:8080
      - IS_HTTPS_SITE
      - SERVER_ACTIONS_ALLOWED_ORIGINS=youdeyiwu:8080
      - SHOW_FOOTER
      - CUSTOM_FOOTER
      - IMAGES_REMOTE_PATTERNS_0_PROTOCOL
      - IMAGES_REMOTE_PATTERNS_0_HOSTNAME
      - IMAGES_REMOTE_PATTERNS_0_PORT
      - IMAGES_REMOTE_PATTERNS_0_PATHNAME
    depends_on:
      - youdeyiwu
    restart: on-failure
    volumes:
      - web_assets:/youdeyiwu-web/public/assets
    ports:
      - "3000:3000"
    networks:
      - youdeyiwu

  youdeyiwu-db:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu database application
    container_name: youdeyiwu-db
    image: 'mysql:8.2'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${DATABASE_USERNAME} --password=${DATABASE_PASSWORD}
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - youdeyiwu

networks:
  youdeyiwu:
    name: youdeyiwu

volumes:
  db:
    name: youdeyiwu_db
  logs:
    name: youdeyiwu_logs
  web_assets:
    name: youdeyiwu_web_assets