INSERT INTO menu_entity (id, created_by, created_on, deleted, updated_by, updated_on, version, link, name, sort)
VALUES (1, null, now(), false, null, now(), 0, '/admin', 'Dashboard', 18),
       (2, null, now(), false, null, now(), 0, '/admin/sections', 'Section Mgmt', 17),
       (3, null, now(), false, null, now(), 0, '/admin/section-groups', 'Section Group Mgmt', 16),
       (4, null, now(), false, null, now(), 0, '/admin/tags', 'Tag Mgmt', 15),
       (5, null, now(), false, null, now(), 0, '/admin/tag-groups', 'Tag Group Mgmt', 14),
       (6, null, now(), false, null, now(), 0, '/admin/posts', 'Post Mgmt', 13),
       (7, null, now(), false, null, now(), 0, '/admin/posts/review-queues', 'Post Review Mgmt', 12),
       (8, null, now(), false, null, now(), 0, '/admin/comments', 'Comment Mgmt', 11),
       (9, null, now(), false, null, now(), 0, '/admin/messages', 'Message Mgmt', 10),
       (10, null, now(), false, null, now(), 0, '/admin/points/rules', 'Point Rule Mgmt', 9),
       (11, null, now(), false, null, now(), 0, '/admin/points/permission-rules', 'Point Perm Mgmt', 8),
       (12, null, now(), false, null, now(), 0, '/admin/users', 'User Mgmt', 7),
       (13, null, now(), false, null, now(), 0, '/admin/roles', 'Role Mgmt', 6),
       (14, null, now(), false, null, now(), 0, '/admin/permissions', 'Permission Mgmt', 5),
       (15, null, now(), false, null, now(), 0, '/admin/menus', 'Menu Mgmt', 4),
       (16, null, now(), false, null, now(), 0, '/admin/submenus', 'Submenu Mgmt', 3),
       (17, null, now(), false, null, now(), 0, '/admin/actions', 'Action Mgmt', 2),
       (18, null, now(), false, null, now(), 0, '/admin/configs', 'Config Mgmt', 1);
