INSERT INTO submenu_entity (id, created_by, created_on, deleted, updated_by, updated_on, version, link, name, sort, menu_id)
VALUES (1, null, now(), false, null, now(), 0, '/admin/sections', 'Dashboard', 2, 2),
       (2, null, now(), false, null, now(), 0, '/admin/sections?type=add', 'Create Section', 1, 2),
       (3, null, now(), false, null, now(), 0, '/admin/section-groups', 'Dashboard', 2, 3),
       (4, null, now(), false, null, now(), 0, '/admin/section-groups?type=add', 'Create Section Group', 1, 3),
       (5, null, now(), false, null, now(), 0, '/admin/tags', 'Dashboard', 2, 4),
       (6, null, now(), false, null, now(), 0, '/admin/tags?type=add', 'Create Tag', 1, 4),
       (7, null, now(), false, null, now(), 0, '/admin/tag-groups', 'Dashboard', 2, 5),
       (8, null, now(), false, null, now(), 0, '/admin/tag-groups?type=add', 'Create Tag Group', 1, 5),
       (9, null, now(), false, null, now(), 0, '/admin/messages', 'Dashboard', 2, 9),
       (10, null, now(), false, null, now(), 0, '/admin/messages?type=add', 'Create Message', 1, 9),
       (11, null, now(), false, null, now(), 0, '/admin/users', 'Dashboard', 2, 12),
       (12, null, now(), false, null, now(), 0, '/admin/users?type=add', 'Create User', 1, 12),
       (13, null, now(), false, null, now(), 0, '/admin/role', 'Dashboard', 2, 13),
       (14, null, now(), false, null, now(), 0, '/admin/roles?type=add', 'Create Role', 1, 13),
       (15, null, now(), false, null, now(), 0, '/admin/permissions', 'Dashboard', 2, 14),
       (16, null, now(), false, null, now(), 0, '/admin/permissions?type=add', 'Create Permission', 1, 14),
       (17, null, now(), false, null, now(), 0, '/admin/menus', 'Dashboard', 2, 15),
       (18, null, now(), false, null, now(), 0, '/admin/menus?type=add', 'Create Menu', 1, 15),
       (19, null, now(), false, null, now(), 0, '/admin/submenus', 'Dashboard', 2, 16),
       (20, null, now(), false, null, now(), 0, '/admin/submenus?type=add', 'Create Submenu', 1, 16),
       (21, null, now(), false, null, now(), 0, '/admin/actions', 'Dashboard', 2, 17),
       (22, null, now(), false, null, now(), 0, '/admin/actions?type=add', 'Create Action', 1, 17);
