INSERT INTO action_entity (id, created_by, created_on, deleted, updated_by, updated_on, version, alias, name, sort, menu_id, submenu_id)
VALUES (1, null, now(), false, null, now(), 0, 'Section Create', 'Sections#Create', 0, 2, null),
       (2, null, now(), false, null, now(), 0, 'Section Update', 'Sections#Update', 0, 2, null),
       (3, null, now(), false, null, now(), 0, 'Section Update States', 'Sections#Update States', 0, 2, null),
       (4, null, now(), false, null, now(), 0, 'Section Update Admins', 'Sections#Update Admins', 0, 2, null),
       (5, null, now(), false, null, now(), 0, 'Section Update Tags', 'Sections#Update Tags', 0, 2, null),
       (6, null, now(), false, null, now(), 0, 'Section Update Tag Groups', 'Sections#Update Tag Groups', 0, 2, null),
       (7, null, now(), false, null, now(), 0, 'Section Groups Create', 'Section Groups#Create', 0, 3, null),
       (8, null, now(), false, null, now(), 0, 'Section Groups Update', 'Section Groups#Update', 0, 3, null),
       (9, null, now(), false, null, now(), 0, 'Section Groups Update Sections', 'Section Groups#Update Sections', 0, 3, null),
       (10, null, now(), false, null, now(), 0, 'Section Groups Delete', 'Section Groups#Delete', 0, 3, null),
       (11, null, now(), false, null, now(), 0, 'Tags Create', 'Tags#Create', 0, 4, null),
       (12, null, now(), false, null, now(), 0, 'Tags Update', 'Tags#Update', 0, 4, null),
       (13, null, now(), false, null, now(), 0, 'Tags Delete', 'Tags#Delete', 0, 4, null),
       (14, null, now(), false, null, now(), 0, 'Tag Groups Create', 'Tag Groups#Create', 0, 5, null),
       (15, null, now(), false, null, now(), 0, 'Tag Groups Update', 'Tag Groups#Update', 0, 5, null),
       (16, null, now(), false, null, now(), 0, 'Tag Groups Update Tags', 'Tag Groups#Update Tags', 0, 5, null),
       (17, null, now(), false, null, now(), 0, 'Tag Groups Delete', 'Tag Groups#Delete', 0, 5, null),
       (18, null, now(), false, null, now(), 0, 'Post Update States', 'Posts#Update States', 0, 6, null),
       (19, null, now(), false, null, now(), 0, 'Post Update Tags', 'Posts#Update Tags', 0, 6, null),
       (20, null, now(), false, null, now(), 0, 'Post Update Section', 'Posts#Update Section', 0, 6, null),
       (21, null, now(), false, null, now(), 0, 'Post Review Receive', 'Post Review Queues#Receive', 0, 7, null),
       (22, null, now(), false, null, now(), 0, 'Post Review Return', 'Post Review Queues#Return', 0, 7, null),
       (23, null, now(), false, null, now(), 0, 'Post Review Approved', 'Post Review Queues#Approved', 0, 7, null),
       (24, null, now(), false, null, now(), 0, 'Post Review NotApproved', 'Post Review Queues#NotApproved', 0, 7, null),
       (25, null, now(), false, null, now(), 0, 'Message Create', 'Messages#Create', 0, 9, null),
       (26, null, now(), false, null, now(), 0, 'Point Rule Update', 'Point Rules#Update', 0, 10, null),
       (27, null, now(), false, null, now(), 0, 'Point Permission Update', 'Point Permissions#Update', 0, 11, null),
       (28, null, now(), false, null, now(), 0, 'Users Create', 'Users#Create', 0, 12, null),
       (29, null, now(), false, null, now(), 0, 'Users Update States', 'Users#Update States', 0, 12, null),
       (30, null, now(), false, null, now(), 0, 'Users Update Roles', 'Users#Update Roles', 0, 12, null),
       (31, null, now(), false, null, now(), 0, 'Users Delete', 'Users#Delete', 0, 12, null),
       (32, null, now(), false, null, now(), 0, 'Roles Create', 'Roles#Create', 0, 13, null),
       (33, null, now(), false, null, now(), 0, 'Roles Update', 'Roles#Update', 0, 13, null),
       (34, null, now(), false, null, now(), 0, 'Roles Update Permissions', 'Roles#Update Permissions', 0, 13, null),
       (35, null, now(), false, null, now(), 0, 'Roles Delete', 'Roles#Delete', 0, 13, null),
       (36, null, now(), false, null, now(), 0, 'Permissions Create', 'Permissions#Create', 0, 14, null),
       (37, null, now(), false, null, now(), 0, 'Permissions Update', 'Permissions#Update', 0, 14, null),
       (38, null, now(), false, null, now(), 0, 'Permissions Update Roles', 'Permissions#Update Roles', 0, 14, null),
       (39, null, now(), false, null, now(), 0, 'Permissions Delete', 'Permissions#Delete', 0, 14, null),
       (40, null, now(), false, null, now(), 0, 'Menus Create', 'Menus#Create', 0, 15, null),
       (41, null, now(), false, null, now(), 0, 'Menus Update', 'Menus#Update', 0, 15, null),
       (42, null, now(), false, null, now(), 0, 'Menus Update Roles', 'Menus#Update Roles', 0, 15, null),
       (43, null, now(), false, null, now(), 0, 'Menus Delete', 'Menus#Delete', 0, 15, null),
       (44, null, now(), false, null, now(), 0, 'Submenus Create', 'Submenus#Create', 0, 16, null),
       (45, null, now(), false, null, now(), 0, 'Submenus Update', 'Submenus#Update', 0, 16, null),
       (46, null, now(), false, null, now(), 0, 'Submenus Update Roles', 'Submenus#Update Roles', 0, 16, null),
       (47, null, now(), false, null, now(), 0, 'Submenus Delete', 'Submenus#Delete', 0, 16, null),
       (48, null, now(), false, null, now(), 0, 'Actions Create', 'Actions#Create', 0, 17, null),
       (49, null, now(), false, null, now(), 0, 'Actions Update', 'Actions#Update', 0, 17, null),
       (50, null, now(), false, null, now(), 0, 'Actions Update Roles', 'Actions#Update Roles', 0, 17, null),
       (51, null, now(), false, null, now(), 0, 'Actions Delete', 'Actions#Delete', 0, 17, null),
       (52, null, now(), false, null, now(), 0, 'JwtConfigs Update', 'JwtConfigs#Update', 0, 18, null),
       (53, null, now(), false, null, now(), 0, 'PointConfigs Update', 'PointConfigs#Update', 0, 18, null);
