INSERT INTO action_entity (id, created_by, created_on, deleted, updated_by, updated_on, version, alias, name, sort, menu_id, role_id, submenu_id)
VALUES (1, null, now(), false, null, now(), 0, 'Section Create', 'Sections#Create', 0, 2, null, null),
       (2, null, now(), false, null, now(), 0, 'Section Update', 'Sections#Update', 0, 2, null, null),
       (3, null, now(), false, null, now(), 0, 'Section Update States', 'Sections#Update States', 0, 2, null, null),
       (4, null, now(), false, null, now(), 0, 'Section Update Admins', 'Sections#Update Admins', 0, 2, null, null),
       (5, null, now(), false, null, now(), 0, 'Section Update Tags', 'Sections#Update Tags', 0, 2, null, null),
       (6, null, now(), false, null, now(), 0, 'Section Update Tag Groups', 'Sections#Update Tag Groups', 0, 2, null, null),
       (7, null, now(), false, null, now(), 0, 'Section Groups Create', 'Section Groups#Create', 0, 3, null, null),
       (8, null, now(), false, null, now(), 0, 'Section Groups Update', 'Section Groups#Update', 0, 3, null, null),
       (9, null, now(), false, null, now(), 0, 'Section Groups Update Sections', 'Section Groups#Update Sections', 0, 3, null, null),
       (10, null, now(), false, null, now(), 0, 'Section Groups Delete', 'Section Groups#Delete', 0, 3, null, null),
       (11, null, now(), false, null, now(), 0, 'Tags Create', 'Tags#Create', 0, 4, null, null),
       (12, null, now(), false, null, now(), 0, 'Tags Update', 'Tags#Update', 0, 4, null, null),
       (13, null, now(), false, null, now(), 0, 'Tags Delete', 'Tags#Delete', 0, 4, null, null),
       (14, null, now(), false, null, now(), 0, 'Tag Groups Create', 'Tag Groups#Create', 0, 5, null, null),
       (15, null, now(), false, null, now(), 0, 'Tag Groups Update', 'Tag Groups#Update', 0, 5, null, null),
       (16, null, now(), false, null, now(), 0, 'Tag Groups Update Tags', 'Tag Groups#Update Tags', 0, 5, null, null),
       (17, null, now(), false, null, now(), 0, 'Tag Groups Delete', 'Tag Groups#Delete', 0, 5, null, null),
       (18, null, now(), false, null, now(), 0, 'Post Update States', 'Posts#Update States', 0, 6, null, null),
       (19, null, now(), false, null, now(), 0, 'Post Update Tags', 'Posts#Update Tags', 0, 6, null, null),
       (20, null, now(), false, null, now(), 0, 'Post Update Section', 'Posts#Update Section', 0, 6, null, null),
       (21, null, now(), false, null, now(), 0, 'Post Review Receive', 'Post Review Queues#Receive', 0, 7, null, null),
       (22, null, now(), false, null, now(), 0, 'Post Review Return', 'Post Review Queues#Return', 0, 7, null, null),
       (23, null, now(), false, null, now(), 0, 'Post Review Approved', 'Post Review Queues#Approved', 0, 7, null, null),
       (24, null, now(), false, null, now(), 0, 'Post Review NotApproved', 'Post Review Queues#NotApproved', 0, 7, null, null),
       (25, null, now(), false, null, now(), 0, 'Message Create', 'Messages#Create', 0, 9, null, null),
       (26, null, now(), false, null, now(), 0, 'Point Rule Update', 'Point Rules#Update', 0, 10, null, null),
       (27, null, now(), false, null, now(), 0, 'Point Permission Update', 'Point Permissions#Update', 0, 11, null, null);

