name: Publishing Youdeyiwu Frontend Application to Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
  workflow_dispatch:

concurrency:
  group: frontend
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: dafengzhen/youdeyiwu-web:dev
