name: Publishing Youdeyiwu Backend Application to Docker

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'hosting/**'
      - 'web/**'
      - 'desktop/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'hosting/**'
      - 'web/**'
      - 'desktop/**'
  workflow_dispatch:

concurrency:
  group: server
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dafengzhen/youdeyiwu:dev
