services:
  youdeyiwu-web:
    labels:
      - maintainer=dafengzhen
      - description=Build youdeyiwu frontend application
    container_name: youdeyiwu-web
    image: "youdeyiwu-web:${TAG}"
    environment:
      - TAG
      - URL
      - NAME
      - DESCRIPTION
      - NEXT_PUBLIC_DEFAULT_LOCALE
      - NEXT_PUBLIC_LOCALES
      - NEXT_PUBLIC_LOCALE_NAMES
      - SHOW_LANGUAGE_SWITCHER
      - API_SERVER
      - IS_HTTPS_SITE
      - SERVER_ACTIONS_ALLOWED_ORIGINS
      - SHOW_FOOTER
      - IMAGES_REMOTE_PATTERNS_0_PROTOCOL
      - IMAGES_REMOTE_PATTERNS_0_HOSTNAME
      - IMAGES_REMOTE_PATTERNS_0_PORT
      - IMAGES_REMOTE_PATTERNS_0_PATHNAME
    build:
      context: .
    networks:
      - frontend
    volumes:
      - web_assets:/youdeyiwu-web/public/assets
    restart: on-failure
    ports:
      - "3000:3000"

networks:
  default:
    name: youdeyiwu_default
  frontend:
    name: youdeyiwu_frontend

volumes:
  web_assets:
